export const LINK_SET_LINKS = 'LINK_SET_LINKS';
export const LINK_ADD_LINK = 'LINK_ADD_LINK';
export const LINK_UPDATE_LINK = 'LINK_UPDATE_LINK';
export const LINK_REMOVE_LINK = 'LINK_REMOVE_LINK';
export const LINK_SET_LINK_INFO = 'LINK_SET_LINK_INFO';
export const LINK_CLEAR_FOR_LOGOUT = 'LINK_CLEAR_FOR_LOGOUT';
